Repository Glovo/glovo-interview-android-base, pull requests merged in 2020-09, with the labels that each got.

#3 Fixed dependencies
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/markdown-navigator-enh.xml
  .idea/markdown-navigator.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  dependencies.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  interview-base-test/.gitignore
  interview-base-test/build.gradle.kts
  interview-base-test/consumer-rules.pro
  interview-base-test/proguard-rules.pro
  interview-base-test/src/main/AndroidManifest.xml
  interview-base-test/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  interview-base/build.gradle.kts
  settings.gradle.kts
Labels: size/L

#4 Added `fragment-ktx` dependency
  dependencies.gradle.kts
Labels: size/XS

#5 Provide 2FA information in the README
  README.md
Labels: size/S
